dose_app/urls.py
from django.urls import path, include
from dose_app import views

# SET THE NAMESPACE!
app_name = 'dose_app'

urlpatterns = [
    # path('pesquisa/', views.pesquisa, name='pesquisa'),
    path('', views.Index.as_view(), name='index'),
    path('test', views.test, name='test'),
    path('pesquisa/', views.SearchView.as_view(), name='pesquisa'),
    path('sobre/', views.sobre, name='sobre'),
    path('config/', views.config, name='config'),
    path('statistic_info/', views.StatisticInfoXA.as_view(), name='info_estatisticas'),
    path('detalhe/<int:pk>/<int:ppk>/', views.XADetailView.as_view(), name='detalhes'),
    path('detalhe/total/pesquisa=<slug:search_name>+<int:pk>+<slug:type>/', views.XATotalDetailView.as_view(), name='detalhes_total'),
    path('detalhe/total/pesquisa=<slug:date_before>+<slug:date_after>+<int:pk>+<slug:type>/', views.XATotalDetailViewData.as_view(), name='detalhes_total_data'),
    path('detalhe/total/agrupado/pesquisa=<slug:search_name>+<slug:id_group>+<slug:type>/', views.XATotalDetailViewGroup.as_view(), name='grupo_detalhes_total'),
    path('detalhe/total/agrupado/pesquisa=<slug:date_before>+<slug:date_after>+<slug:id_group>+<slug:type>/', views.XATotalDetailViewGroupData.as_view(), name='grupo_detalhes_total_data'),
    path('lista/pesquisa=<slug:search_name>', views.StudyListView.as_view(), name='lista'),
    path('lista/pesquisa=<slug:date_before>+<slug:date_after>', views.StudyListViewByDate.as_view(), name='lista_data'),
    path('comm/in/', views.hucam_server_comm_in, name='comm_in'),
    path('comm/out.json', views.hucam_server_comm_out, name='comm_out'),
    path('comm/update', views.hucam_server_comm_update, name='atualizar')

]

hucam_dose_local/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('dose_app.urls')),
    path('comm/login/', views.LoginView.as_view(), name='login'),

]

dose_app/models.py
from django.db import models
import datetime
#from django.core.urlresolvers import reverse


# Create your models here.
class ModelPatient(models.Model):

    name = models.CharField(max_length=256)
    name_for_URL = models.CharField(max_length=256)
    dob = models.CharField(max_length=128)
    dob_parsed = models.DateField(default=datetime.date(9999,12,30))
    sex = models.CharField(max_length=128)

    number_of_studies = models.PositiveIntegerField(default=0)
    dose_PKA_complete = models.DecimalField(decimal_places=2, max_digits=64, default=0)
    dose_KAPR_complete = models.DecimalField(decimal_places=2, max_digits=64, default=0)

    deleted = models.BooleanField(default=False)
    mistaken = models.BooleanField(default=False)


class ModelStudyXA(models.Model):

    patient = models.ForeignKey(ModelPatient, related_name='xa_studies', on_delete=models.CASCADE)

    uid = models.CharField(max_length=256)

    institution = models.CharField(max_length=256, default='HUCAM')

    kv = models.IntegerField(default=0)

    study_date = models.CharField(max_length=128)
    study_date_parsed = models.DateField(default=datetime.date(9999,12,30))

    study_time = models.CharField(max_length=32, default="000000.000000")
    study_time_parsed = models.TimeField(default=datetime.time(0,0,0))

    dose_KAPR_total = models.DecimalField(decimal_places=2, max_digits=64)
    dose_PKA_total = models.DecimalField(decimal_places=2, max_digits=64)

    fluoro_KAPR_total = models.DecimalField(decimal_places=2, max_digits=64)
    fluoro_PKA_total = models.DecimalField(decimal_places=2, max_digits=64)

    acq_KAPR_total = models.DecimalField(decimal_places=2, max_digits=64)
    acq_PKA_total = models.DecimalField(decimal_places=2, max_digits=64)

    fluoro_time_total = models.DecimalField(decimal_places=2, max_digits=64)
    acq_time_total = models.DecimalField(decimal_places=2, max_digits=64)

    deleted = models.BooleanField(default=False)
    mistaken = models.BooleanField(default=False)


class ModelRequestName(models.Model):
    name = models.CharField(max_length=15000, default='', blank=True )
    full_info = models.TextField(max_length=32768, default='', blank=True)
    priority = models.PositiveIntegerField(default=0)
    ready = models.BooleanField(default=False)


class ModelRequestUIDs(models.Model):
    uids = models.CharField(max_length=4096, default='', blank=True)
    full_info = models.TextField(max_length=32768, default='', blank=True)
    priority = models.PositiveIntegerField(default=0)
    ready = models.BooleanField(default=False)


class ModelRequestDateFixed(models.Model):
    days_back = models.PositiveIntegerField(default=0)
    months_back = models.PositiveIntegerField(default=0)
    full_info = models.TextField(max_length=32768, default='', blank=True)
    priority = models.PositiveIntegerField(default=0)
    ready = models.BooleanField(default=False)


class ModelRequestDatePeriod(models.Model):
    date_before = models.CharField(max_length=256, default='', blank=True )
    date_after = models.CharField(max_length=256, default='', blank=True )
    full_info = models.TextField(max_length=32768, default='', blank=True)
    priority = models.PositiveIntegerField(default=0)
    ready = models.BooleanField(default=False)


class ModelDeletedUID(models.Model):
    del_uid = models.CharField(max_length=256)

dose_app/forms.py
from django import forms


class SearchForm(forms.Form):
    search_name = forms.CharField(required=False)

    def as_p(self):
        "Returns this form rendered as HTML <p>s."
        return self._html_output(
            normal_row=u'<tr><td><input type="text" class="form-control" name="search_name" '
                       u'placeholder="NOME COMPLETO" id="id_search_name" required /></td>',
            error_row=u'%s',
            row_ender='</tr>',
            help_text_html=u' <span class="helptext">%s</span>',
            errors_on_separate_row=True)


class NameListForm(forms.Form):
    group_checkboxes = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
    )
    delete_checkboxes = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
    )


class IndexForm(forms.Form):
    pass

templates/dose_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HUCAM Doses</title>

    <!---*** Start: JQuery 3.3.1 version. ***--->
    <script language="javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!---*** End: JQuery 3.3.1 version. ***--->
    <!---*** Start: Bootstrap 3.3.7 version files. ***--->
    <script language="javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!---*** End: Bootstrap 3.3.7 version files. ***--->

    <script language="javascript" src="https://momentjs.com/downloads/moment.js"></script>
    <script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css">

    {% block head_block %}
    {% endblock %}

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">

                {# HUCAM Doses Pagina Principal / Pesquisa / Informações Gerais / Sobre / Configuracoes #}
                <li> <a class="navbar-brand" href="{%  url 'dose_app:index' %}">
                    <img src="{%  static "dose_app/images/logo_hucam_radioprotecao.png" %}" alt="Missing_FILE" style="padding:-5px;margin:-10px;width:63px;height:42px;">
                </a> </li>
                <li> <a class="navbar-link" href="{%  url 'dose_app:pesquisa' %}">Pesquisa</a> </li>
                <li> <a class="navbar-link" href="{%  url 'dose_app:info_estatisticas' %}">Informações Estatísticas</a> </li>
                <li> <a class="navbar-link" href="{%  url 'dose_app:sobre' %}">Sobre</a> </li>
                <li> <a class="navbar-link" href="{%  url 'dose_app:config' %}">Configurações</a> </li>

            </ul>
        </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


</body>
</html>

templates/dose_app/comm_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
    <form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class='btn btn-primary' value="Login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
</body>
</html>

templates/dose_app/configs.html
{% extends "dose_app/modelo_base.html" %}

{% block col1 %}


        <div class="jumbotron">
            <h1> Aba em construção, pedimos desculpas pela inconveniência</h1>
        </div>

{% endblock %}

templates/dose_app/detalhe_estudo_total_data.html
{% extends "dose_app/detalhe_estudo_total.html" %}

{% block back_button %}
<div style="background:transparent !important" class="jumbotron">
    <a href="{% url 'dose_app:lista_data' date_before=view.kwargs.date_before date_after=view.kwargs.date_after %}" style="width: 200px" class="btn btn-danger center-block btn-lg">Voltar</a>
</div>
{% endblock %}

templates/dose_app/email_patient_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<style>
    table, th, td {
    border: 1px solid black;
    text-align: center;
}
</style>

<table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Data de nascimento</th>
                <th>Kerma no ar (mGy)</th>
                <th>Produto kerma-área (µGym²)</th>
                <th>Número de estudos</th>
            </tr>
        </thead>
        <tboody>
            {% for patient in qs %}
                <tr>
                    <td> {{ patient.name }} </td>
                    <td> {{ patient.dob_parsed }} </td>
                    <td> {{ patient.dose_KAPR_complete }} </td>
                    <td> {{ patient.dose_PKA_complete }} </td>
                    <td> {{ patient.number_of_studies }} </td>
                </tr>
            {% endfor %}
        </tboody>

    </table>


</body>
</html>

templates/dose_app/index.html
{% extends "dose_app/modelo_base.html" %}
{% load staticfiles %}
{% block col1 %}

    <div class="jumbotron">
        <form accept-charset="UTF-8" method="post" style="padding-top: 5px" onsubmit="$('#target').toggle();">
            {% csrf_token %}
            <h1 style="font-size: 400%; margin-top: -20px"> Bem vindo ao site de pesquisa de doses do HUCAM </h1>
            <div style="text-align:justify;">
                <h3> Para pesquisar sobre dados entre na aba de Pesquisa</h3>
                <h3> Para saber mais sobre o site entre em Sobre</h3>
                <span class="hr" style="display: block;flex: 1;height: 3px;background: #D4D4D4;"></span>
                <h3><b>Atualizar Site:</b></h3>

            </div>
                <div class="custom-control custom-radio">
                  <input type="radio" class="custom-control-input" id="radioDesdeInicio" checked name="radioDatabaseUpd">
                  <label class="custom-control-label" for="radioDesdeInicio" style="margin-top: -1px;vertical-align: middle;">Desde Início</label>

                  <input type="radio" class="custom-control-input" id="radioData" name="radioDatabaseUpd" style="margin-left: 10px">
                  <input type="text" class="form-control" name='radioDataInput' style="width:105px; height:30px; display:inline" placeholder="aaaa-mm-dd" autocomplete="off"/>
                </div>

            <div class="row">
                <div class="col-md-3">
                <input class="btn btn-primary" type="submit" value="Atualizar Banco de Dados" name="btn_db_update" style="padding:8px; margin-top:10px; width:180px"/>
                </div>
                <div class="col-md-5"></div>
                <div class="col-md-3">
                <input class="btn btn-warning" type="submit" value="Atualizar Programa" name="btn_prog_update"
                       style="padding:8px;margin-left:42px;margin-top:10px; width:180px"/>
                </div>
            </div>

        </form>
    </div>
    {# <a href={%  url 'dose_app:test' %}>clicke aqui</a> #}

{% endblock %}

{% block col-lateral %}
    <img src="{%  static "dose_app/images/logo_radioprotecao.png" %}" alt="Missing_FILE" style="height: 150%;width: 150%;margin-left: -20px">
    <img src="{%  static "dose_app/images/HUCAm.png" %}" alt="Missing_FILE" style="height: 110%;width: 110%;margin-left: 30px; margin-top: 40px">
{% endblock %}

templates/dose_app/lista_estudos.html
{% extends "dose_app/base.html" %}
{% load staticfiles %}


{% block head_block %}
    <link rel="stylesheet" href="{% static 'dose_app/css/lista_estudos.css' %}" >
    <script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
    </script>
    <script>
    $(function(){
      $(".not-clickable-cell").click(function(event) {
       event.stopPropagation();
    });
    });
    </script>
{%  endblock %}

{% block body_block %}

    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#home">Lista por Paciente</a></li>
      <li><a data-toggle="tab" href="#menu1">Lista por Estudo</a></li>
    </ul>

    <div class="tab-content">
      <div id="home" class="tab-pane fade in active">
        <form action="" method="post">
           {% csrf_token %}
            <div class="jumbotron">
                <div class="row">
                    <div ><h2 class="col-md-10" style="margin-top:-10px; margin-bottom: 20px">Resultados obtidos: </h2></div>
                </div>
                <div class="row">
                    <div ><label class="col-md-8">Nome - Data de nascimento </label></div>
                    <div ><label class="col-md-2">Número de estudos </label></div>
                    <div ><label class="col-md-1" >Agrupar</label></div>
                    <div ><label class="col-md-1" >Deletar</label></div>
                </div>


                {% for patient in patient_list %}
                    <div class="row">
                      <div class="panel-group col-xs-10">
                      <div class="panel panel-default">
                        <div class="panel-heading" style="cursor:pointer;">
                          <h4 class="panel-title">
                              <text class="accordion-toggle" data-toggle="collapse" href="#{{ patient.id }}">{{patient.name}} - {{ patient.dob_parsed }} <span style="float: right">{{ patient.number_of_studies }}</span></text>
                          </h4>
                        </div>
                        <div id="{{ patient.id }}" class="panel-collapse collapse">
                          <ul class="list-group" style="cursor:pointer;">
                              {% for patient_study in patient.xa_studies.all %}
                                  <a class="list-group-item list-group-item-action" href="{% url 'dose_app:detalhes' pk=patient.id ppk=patient_study.id %}">{{ patient_study.study_date_parsed }} | Dose total: {{ patient_study.dose_KAPR_total }} mGy & {{ patient_study.dose_PKA_total }} μGym²</a>
                              {% endfor %}
                              {% block date_link %}
                              <a class="list-group-item list-group-item-action list-group-item-info" href="{% url 'dose_app:detalhes_total' search_name=view.kwargs.search_name pk=patient.id type='p'%}">Todos os estudos</a>
                              {% endblock %}
                          </ul>
                        </div>
                      </div>
                      </div>

                    <div><label class="checkbox-inline col-xs-1" style="padding-left:55px"><input type="checkbox" name="group_checkboxes" value="{{ patient.id }}"></label></div>
                    <div><label class="checkbox-inline col-xs-1" style="padding-left:50px"><input type="checkbox" name="delete_checkboxes" value="{{ patient.id }}"></label></div>

                    </div>
               {% endfor %}
            <div class="row">
                <div class="col-xs-10"></div>
                <div class="col-xs-1"><input style="padding-left:15px;padding-right:15px;margin-left:7px" type="submit" value="A" name="group" class="btn btn-xs btn-primary"></div>
                <div class="col-xs-1"><input style="padding-left:15px;padding-right:15px;margin-left:2px" type="submit" value="D" name="delete" class="btn btn-xs btn-danger"></div>

            </div>
            </div>
       </form>
      </div>

      <div id="menu1" class="tab-pane fade">
        <form action="" method="post">
        {% csrf_token %}
        <div class="jumbotron">
            <div class="row">
                <div ><h2 class="col-md-12" style="margin-top: -10px">Resultados obtidos: </h2></div>
            </div>
        <table class="table table-bordered table-hover small" id="table_list_view">
            <thead>
            <tr>
                <th style="text-align: center;vertical-align: middle;">DATA DO ESTUDO</th>
                <th style="text-align: center;vertical-align: middle;">HORA DO ESTUDO</th>
                <th style="text-align: center;vertical-align: middle;">NOME DO PACIENTE</th>
                <th style="text-align: center;vertical-align: middle;">DATA DE NASCIMENTO</th>
                <th style="text-align: center;vertical-align: middle;">PKA TOTAL</th>
                <th style="text-align: center;vertical-align: middle;">KAPR TOTAL</th>
                <th style="text-align: center;vertical-align: middle;">AGRUPAR</th>
                <th style="text-align: center;vertical-align: middle;padding:5px">DELETAR</th>
            </tr>
            </thead>
            <tbody>
            {% for study in study_list %}
                <tr class="text-center clickable-row" style="cursor: pointer" data-href="{% url 'dose_app:detalhes' pk=study.patient.id ppk=study.id %}"></a>
                    <td>{{ study.study_date_parsed }}</td>
                    <td>{{ study.study_time_parsed }}</td>
                    <td>{{ study.patient.name }}</td>
                    <td>{{ study.patient.dob_parsed }}</td>
                    <td>{{ study.dose_PKA_total }}</td>
                    <td>{{ study.dose_KAPR_total }}</td>

                    <td style="text-align: center" class="not-clickable-cell"><input type="checkbox" name="group_checkboxes_study" value="{{ study.id }}"></td>
                    <td style="text-align: center" class="not-clickable-cell"><input type="checkbox" name="delete_checkboxes_study" value="{{ study.id }}"></td>
                </tr>
            {% endfor %}
            </tbody>
       </table>
        <div class="row">
            <div class="col-xs-10"></div>
            <div class="col-xs-1"><input style="padding-left:15px;padding-right:15px;margin-left:7px" type="submit" value="A" name="group" class="btn btn-xs btn-primary"></div>
            <div class="col-xs-1"><input style="padding-left:15px;padding-right:15px;margin-left:2px" type="submit" value="D" name="delete" class="btn btn-xs btn-danger"></div>

        </div>
        </div>
      </form>
      </div>

    </div>

    <div style="background:transparent !important" class="jumbotron">
    <a href="{% url 'dose_app:pesquisa' %}" style="width: 200px" class="btn btn-danger center-block btn-lg">Voltar</a>
    </div>

{% endblock %}

templates/dose_app/lista_estudos_data.html
{% extends "dose_app/lista_estudos.html" %}

{% block date_link %}
<a class="list-group-item list-group-item-action list-group-item-info" href="{% url 'dose_app:detalhes_total_data' date_before=view.kwargs.date_before date_after=view.kwargs.date_after pk=patient.id type='p'%}">Todos os estudos</a>
{% endblock %}

templates/dose_app/patient_change_list.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    <style>
    #object-tools-items_css {
        display: block;
        float: left;
        padding: 3px 12px;
        background: #999;
        font-weight: 400;
        font-size: 11px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        color: #fff;
        border-radius: 15px;
        border: 0px;
        text-decoration: none;
        line-height: 20px;
        cursor: pointer;
    }
    #object-tools-items_css:hover{
        background: #447e9b;
    }
    </style>

    <li>
        <form action="sendEmail/" method="POST">
            {% csrf_token %}
          <button type='submit' id="object-tools-items_css">
            Send e-mail with Patients in Alert
          </button>
        </form>
        </li>

    {{ block.super }}
{% endblock %}

templates/dose_app/pesquisa.html
{% extends "dose_app/base.html" %}
{% load staticfiles %}

{% block head_block %}

    <link rel="stylesheet" href="{% static 'dose_app/css/pesquisa.css' %}" >

    <script>
    $( function() {
    $( ".datepick" ).datetimepicker({
        format: 'YYYY-MM-DD',
        ignoreReadonly: true
    });
    });
    </script>

{% endblock %}

{% block body_block %}

    <div class="jumbotron">

    <h2>Insira um nome:</h2>

    <form accept-charset="UTF-8" method="post" style="padding-top: 5px" onsubmit="$('#target').toggle();">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-5">
                {{ form.as_p }}
            </div>
            <div class="col-md-7">
                <div class="loader" id="target" style="display:none"></div>
            </div>
        </div>
        <input class="btn btn-primary" type="submit" value="Pesquisar" name="btn_name" style="padding:8px; margin-top:10px"/>
    </form>

    </div>
     <div class="jumbotron">

    <h2>Insira uma data:</h2>

    <form accept-charset="UTF-8" method="post" style="padding-top: 5px" onsubmit="$('#target2').toggle();">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-5" style="padding-left: 15px">
                <div class="input-group">
                    {% if request.GET.date_before and request.GET.date_after %}

                        <div class="input-group datepick">
                            <input type="text" class="form-control" name='date_before' style="margin-top:1px;margin-bottom:-1px; height:35px;" value="{{ request.GET.date_before }}" autocomplete="off"/>
                            <span class="input-group-addon glyphicon glyphicon-calendar" ></span>
                        </div>

                         <span class="input-group-addon" style="padding: 10px;margin: 10px;border: 10px">-</span>

                        <div class="input-group datepick">
                            <input type="text" class="form-control" name='date_after' style="margin-top:1px;margin-bottom:-1px; height:35px;" value="{{ request.GET.date_after }}" autocomplete="off"/>
                            <span class="input-group-addon glyphicon glyphicon-calendar" ></span>
                        </div>

                    {% else %}

                        <div class="input-group datepick">
                            <input type="text" class="form-control" name='date_before' style="margin-top:1px;margin-bottom:-1px; height:35px;" placeholder="aaaa-mm-dd" required autocomplete="off"/>
                            <span class="input-group-addon glyphicon glyphicon-calendar" ></span>
                        </div>

                        <span class="input-group-addon" style="padding: 10px;margin: 10px;border: 10px">-</span>

                        <div class="input-group datepick">
                            <input type="text" class="form-control" name='date_after' style="margin-top:1px;margin-bottom:-1px; height:35px;" placeholder="aaaa-mm-dd" required autocomplete="off"/>
                            <span class="input-group-addon glyphicon glyphicon-calendar" ></span>
                        </div>

                    {% endif %}
                </div>
            </div>
            <div class="col-md-7">
                <div class="loader" id="target2" style="display:none; margin-top:4px"></div>
            </div>
        </div>
        <input class="btn btn-primary" type="submit" value="Pesquisar" name="btn_date"  style="padding:8px; margin-top:10px" />
    </form>

    </div>
    <div style="background:transparent !important" class="jumbotron">
    <a href="{% url 'dose_app:index' %}" style="width: 200px" class="btn btn-danger center-block btn-lg">Voltar</a>
    </div>
{% endblock %}

templates/dose_app/test.html
{% extends "dose_app/base.html" %}
{% load staticfiles %}


{% block head_block %}
    <link rel="stylesheet" href="{% static 'dose_app/css/lista_estudos.css' %}" >
    <script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
    </script>
    <script>
    $(function(){
      $(".not-clickable-cell").click(function(event) {
       event.stopPropagation();
    });
    });
    </script>
{%  endblock %}

{% block body_block %}
   <form action="" method="post">
   {% csrf_token %}
    <div class="jumbotron">
        <div class="row">
            <div ><h2 class="col-md-10">Resultados obtidos: </h2></div>
            <div ><label class="col-md-1" style="margin-top:30px;">Agrupar</label></div>
            <div ><label class="col-md-1" style="margin-top:30px;">Deletar</label></div>
        </div>
    <table class="table table-bordered table-hover small" id="table_list_view">
        <thead>
        <tr>
            <th style="text-align: center;vertical-align: middle;">DATA DO ESTUDO</th>
            <th style="text-align: center;vertical-align: middle;">HORA DO ESTUDO</th>
            <th style="text-align: center;vertical-align: middle;">NOME DO PACIENTE</th>
            <th style="text-align: center;vertical-align: middle;">DATA DE NASCIMENTO</th>
            <th style="text-align: center;vertical-align: middle;">PKA TOTAL</th>
            <th style="text-align: center;vertical-align: middle;">KAPR TOTAL</th>
            <th style="text-align: center;vertical-align: middle;">AGRUPAR</th>
            <th style="text-align: center;vertical-align: middle;padding:5px">DELETAR</th>
        </tr>
        </thead>
        <tbody>
        {% for study in study_list %}
            <tr class="text-center clickable-row" style="cursor: pointer" data-href="{% url 'dose_app:detalhes' pk=study.patient.id ppk=study.id %}"></a>
                <td>{{ study.study_date_parsed }}</td>
                <td>{{ study.study_time_parsed }}</td>
                <td>{{ study.patient.name }}</td>
                <td>{{ study.patient.dob_parsed }}</td>
                <td>{{ study.dose_PKA_total }}</td>
                <td>{{ study.dose_KAPR_total }}</td>

                <td style="text-align: center" class="not-clickable-cell"><input type="checkbox" name="group_checkboxes" value="{{ study.patient.id }}"></td>
                <td style="text-align: center" class="not-clickable-cell"><input type="checkbox" name="delete_checkboxes" value="{{ study.patient.id }}"></td>
            </tr>

        {% endfor %}
        </tbody>
   </table>
    <div class="row">
        <div class="col-xs-10"></div>
        <div class="col-xs-1"><input style="padding-left:15px;padding-right:15px;margin-left:7px" type="submit" value="A" name="group" class="btn btn-xs btn-primary"></div>
        <div class="col-xs-1"><input style="padding-left:15px;padding-right:15px;margin-left:2px" type="submit" value="D" name="delete" class="btn btn-xs btn-danger"></div>

    </div>
    </div>
   </form>
    <div style="background:transparent !important" class="jumbotron">
    <a href="{% url 'dose_app:pesquisa' %}" style="width: 200px" class="btn btn-danger center-block btn-lg">Voltar</a>
    </div>

{% endblock %}

<div class="row">
    <div class="col-md-12">
    <div class="progress" style="margin-top: 20px">
      <div id='dynamic' class="progress-bar progress-bar-striped active" role="progressbar"
      aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%">
          <span id="current-progress"></span>
      </div>
    </div>
    </div>
</div>